#  spring.application.name=netflix-eureka-naming-server
#    server.port=8761
#    eureka.client.register-with-eureka=false
#    eureka.client.fetch-registry=false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


server:
  port: 8761
